creation_rules:
  - path_regex: packages/env/\.env\.sops$
    age:
      # Revanth Pothukuchi
      - age1skz60ndmyn9wzc55sfvwt7we3hrmeheppeva2kelf5krlmgu0vvq20cn4w
      # Hari Charan
      - age1dqs29u24l8mj2k7qw3n64nadw8tt35cyhay4s4sv83kagzn76ycqz3mt5f