creation_rules:
  - path_regex: packages/env/\.env\.sops$
    age:
      # Revanth Pothukuchi
      - age1skz60ndmyn9wzc55sfvwt7we3hrmeheppeva2kelf5krlmgu0vvq20cn4w
      # Hari Charan
      - age1wzjrz7yg25rwdl58fj4kzhzct08lmsc9m376sxnsynj7npqahycsz8drcv