import type { PhoneCountry } from './phone-countries'

// Generated from country-state-city's Country.getAllCountries() — see the script referenced
// in phone-countries.ts. Kept as a plain literal rather than importing the package at runtime
// because its ESM entry barrels Country, State, and City together: pulling in Country for
// dial codes drags State's ~550KB dataset along with it, even on pages (like /login) that
// never render a state picker.
export const PHONE_COUNTRIES_DATA: PhoneCountry[] = [
  { isoCode: 'AF', name: 'Afghanistan', dialCode: '93', flag: '🇦🇫' },
  { isoCode: 'AX', name: 'Aland Islands', dialCode: '358-18', flag: '🇦🇽' },
  { isoCode: 'AL', name: 'Albania', dialCode: '355', flag: '🇦🇱' },
  { isoCode: 'DZ', name: 'Algeria', dialCode: '213', flag: '🇩🇿' },
  { isoCode: 'AS', name: 'American Samoa', dialCode: '1-684', flag: '🇦🇸' },
  { isoCode: 'AD', name: 'Andorra', dialCode: '376', flag: '🇦🇩' },
  { isoCode: 'AO', name: 'Angola', dialCode: '244', flag: '🇦🇴' },
  { isoCode: 'AI', name: 'Anguilla', dialCode: '1-264', flag: '🇦🇮' },
  { isoCode: 'AQ', name: 'Antarctica', dialCode: '672', flag: '🇦🇶' },
  { isoCode: 'AG', name: 'Antigua And Barbuda', dialCode: '1-268', flag: '🇦🇬' },
  { isoCode: 'AR', name: 'Argentina', dialCode: '54', flag: '🇦🇷' },
  { isoCode: 'AM', name: 'Armenia', dialCode: '374', flag: '🇦🇲' },
  { isoCode: 'AW', name: 'Aruba', dialCode: '297', flag: '🇦🇼' },
  { isoCode: 'AU', name: 'Australia', dialCode: '61', flag: '🇦🇺' },
  { isoCode: 'AT', name: 'Austria', dialCode: '43', flag: '🇦🇹' },
  { isoCode: 'AZ', name: 'Azerbaijan', dialCode: '994', flag: '🇦🇿' },
  { isoCode: 'BH', name: 'Bahrain', dialCode: '973', flag: '🇧🇭' },
  { isoCode: 'BD', name: 'Bangladesh', dialCode: '880', flag: '🇧🇩' },
  { isoCode: 'BB', name: 'Barbados', dialCode: '1-246', flag: '🇧🇧' },
  { isoCode: 'BY', name: 'Belarus', dialCode: '375', flag: '🇧🇾' },
  { isoCode: 'BE', name: 'Belgium', dialCode: '32', flag: '🇧🇪' },
  { isoCode: 'BZ', name: 'Belize', dialCode: '501', flag: '🇧🇿' },
  { isoCode: 'BJ', name: 'Benin', dialCode: '229', flag: '🇧🇯' },
  { isoCode: 'BM', name: 'Bermuda', dialCode: '1-441', flag: '🇧🇲' },
  { isoCode: 'BT', name: 'Bhutan', dialCode: '975', flag: '🇧🇹' },
  { isoCode: 'BO', name: 'Bolivia', dialCode: '591', flag: '🇧🇴' },
  { isoCode: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dialCode: '599', flag: '🇧🇶' },
  { isoCode: 'BA', name: 'Bosnia and Herzegovina', dialCode: '387', flag: '🇧🇦' },
  { isoCode: 'BW', name: 'Botswana', dialCode: '267', flag: '🇧🇼' },
  { isoCode: 'BV', name: 'Bouvet Island', dialCode: '0055', flag: '🇧🇻' },
  { isoCode: 'BR', name: 'Brazil', dialCode: '55', flag: '🇧🇷' },
  { isoCode: 'IO', name: 'British Indian Ocean Territory', dialCode: '246', flag: '🇮🇴' },
  { isoCode: 'BN', name: 'Brunei', dialCode: '673', flag: '🇧🇳' },
  { isoCode: 'BG', name: 'Bulgaria', dialCode: '359', flag: '🇧🇬' },
  { isoCode: 'BF', name: 'Burkina Faso', dialCode: '226', flag: '🇧🇫' },
  { isoCode: 'BI', name: 'Burundi', dialCode: '257', flag: '🇧🇮' },
  { isoCode: 'KH', name: 'Cambodia', dialCode: '855', flag: '🇰🇭' },
  { isoCode: 'CM', name: 'Cameroon', dialCode: '237', flag: '🇨🇲' },
  { isoCode: 'CA', name: 'Canada', dialCode: '1', flag: '🇨🇦' },
  { isoCode: 'CV', name: 'Cape Verde', dialCode: '238', flag: '🇨🇻' },
  { isoCode: 'KY', name: 'Cayman Islands', dialCode: '1-345', flag: '🇰🇾' },
  { isoCode: 'CF', name: 'Central African Republic', dialCode: '236', flag: '🇨🇫' },
  { isoCode: 'TD', name: 'Chad', dialCode: '235', flag: '🇹🇩' },
  { isoCode: 'CL', name: 'Chile', dialCode: '56', flag: '🇨🇱' },
  { isoCode: 'CN', name: 'China', dialCode: '86', flag: '🇨🇳' },
  { isoCode: 'CX', name: 'Christmas Island', dialCode: '61', flag: '🇨🇽' },
  { isoCode: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '61', flag: '🇨🇨' },
  { isoCode: 'CO', name: 'Colombia', dialCode: '57', flag: '🇨🇴' },
  { isoCode: 'KM', name: 'Comoros', dialCode: '269', flag: '🇰🇲' },
  { isoCode: 'CG', name: 'Congo', dialCode: '242', flag: '🇨🇬' },
  { isoCode: 'CK', name: 'Cook Islands', dialCode: '682', flag: '🇨🇰' },
  { isoCode: 'CR', name: 'Costa Rica', dialCode: '506', flag: '🇨🇷' },
  { isoCode: 'CI', name: "Cote D'Ivoire (Ivory Coast)", dialCode: '225', flag: '🇨🇮' },
  { isoCode: 'HR', name: 'Croatia', dialCode: '385', flag: '🇭🇷' },
  { isoCode: 'CU', name: 'Cuba', dialCode: '53', flag: '🇨🇺' },
  { isoCode: 'CW', name: 'Curaçao', dialCode: '599', flag: '🇨🇼' },
  { isoCode: 'CY', name: 'Cyprus', dialCode: '357', flag: '🇨🇾' },
  { isoCode: 'CZ', name: 'Czech Republic', dialCode: '420', flag: '🇨🇿' },
  { isoCode: 'CD', name: 'Democratic Republic of the Congo', dialCode: '243', flag: '🇨🇩' },
  { isoCode: 'DK', name: 'Denmark', dialCode: '45', flag: '🇩🇰' },
  { isoCode: 'DJ', name: 'Djibouti', dialCode: '253', flag: '🇩🇯' },
  { isoCode: 'DM', name: 'Dominica', dialCode: '1-767', flag: '🇩🇲' },
  { isoCode: 'DO', name: 'Dominican Republic', dialCode: '1-809 and 1-829', flag: '🇩🇴' },
  { isoCode: 'TL', name: 'East Timor', dialCode: '670', flag: '🇹🇱' },
  { isoCode: 'EC', name: 'Ecuador', dialCode: '593', flag: '🇪🇨' },
  { isoCode: 'EG', name: 'Egypt', dialCode: '20', flag: '🇪🇬' },
  { isoCode: 'SV', name: 'El Salvador', dialCode: '503', flag: '🇸🇻' },
  { isoCode: 'GQ', name: 'Equatorial Guinea', dialCode: '240', flag: '🇬🇶' },
  { isoCode: 'ER', name: 'Eritrea', dialCode: '291', flag: '🇪🇷' },
  { isoCode: 'EE', name: 'Estonia', dialCode: '372', flag: '🇪🇪' },
  { isoCode: 'ET', name: 'Ethiopia', dialCode: '251', flag: '🇪🇹' },
  { isoCode: 'FK', name: 'Falkland Islands', dialCode: '500', flag: '🇫🇰' },
  { isoCode: 'FO', name: 'Faroe Islands', dialCode: '298', flag: '🇫🇴' },
  { isoCode: 'FJ', name: 'Fiji Islands', dialCode: '679', flag: '🇫🇯' },
  { isoCode: 'FI', name: 'Finland', dialCode: '358', flag: '🇫🇮' },
  { isoCode: 'FR', name: 'France', dialCode: '33', flag: '🇫🇷' },
  { isoCode: 'GF', name: 'French Guiana', dialCode: '594', flag: '🇬🇫' },
  { isoCode: 'PF', name: 'French Polynesia', dialCode: '689', flag: '🇵🇫' },
  { isoCode: 'TF', name: 'French Southern Territories', dialCode: '262', flag: '🇹🇫' },
  { isoCode: 'GA', name: 'Gabon', dialCode: '241', flag: '🇬🇦' },
  { isoCode: 'GE', name: 'Georgia', dialCode: '995', flag: '🇬🇪' },
  { isoCode: 'DE', name: 'Germany', dialCode: '49', flag: '🇩🇪' },
  { isoCode: 'GH', name: 'Ghana', dialCode: '233', flag: '🇬🇭' },
  { isoCode: 'GI', name: 'Gibraltar', dialCode: '350', flag: '🇬🇮' },
  { isoCode: 'GR', name: 'Greece', dialCode: '30', flag: '🇬🇷' },
  { isoCode: 'GL', name: 'Greenland', dialCode: '299', flag: '🇬🇱' },
  { isoCode: 'GD', name: 'Grenada', dialCode: '1-473', flag: '🇬🇩' },
  { isoCode: 'GP', name: 'Guadeloupe', dialCode: '590', flag: '🇬🇵' },
  { isoCode: 'GU', name: 'Guam', dialCode: '1-671', flag: '🇬🇺' },
  { isoCode: 'GT', name: 'Guatemala', dialCode: '502', flag: '🇬🇹' },
  { isoCode: 'GG', name: 'Guernsey and Alderney', dialCode: '44-1481', flag: '🇬🇬' },
  { isoCode: 'GN', name: 'Guinea', dialCode: '224', flag: '🇬🇳' },
  { isoCode: 'GW', name: 'Guinea-Bissau', dialCode: '245', flag: '🇬🇼' },
  { isoCode: 'GY', name: 'Guyana', dialCode: '592', flag: '🇬🇾' },
  { isoCode: 'HT', name: 'Haiti', dialCode: '509', flag: '🇭🇹' },
  { isoCode: 'HM', name: 'Heard Island and McDonald Islands', dialCode: '672', flag: '🇭🇲' },
  { isoCode: 'HN', name: 'Honduras', dialCode: '504', flag: '🇭🇳' },
  { isoCode: 'HK', name: 'Hong Kong S.A.R.', dialCode: '852', flag: '🇭🇰' },
  { isoCode: 'HU', name: 'Hungary', dialCode: '36', flag: '🇭🇺' },
  { isoCode: 'IS', name: 'Iceland', dialCode: '354', flag: '🇮🇸' },
  { isoCode: 'IN', name: 'India', dialCode: '91', flag: '🇮🇳' },
  { isoCode: 'ID', name: 'Indonesia', dialCode: '62', flag: '🇮🇩' },
  { isoCode: 'IR', name: 'Iran', dialCode: '98', flag: '🇮🇷' },
  { isoCode: 'IQ', name: 'Iraq', dialCode: '964', flag: '🇮🇶' },
  { isoCode: 'IE', name: 'Ireland', dialCode: '353', flag: '🇮🇪' },
  { isoCode: 'IL', name: 'Israel', dialCode: '972', flag: '🇮🇱' },
  { isoCode: 'IT', name: 'Italy', dialCode: '39', flag: '🇮🇹' },
  { isoCode: 'JM', name: 'Jamaica', dialCode: '1-876', flag: '🇯🇲' },
  { isoCode: 'JP', name: 'Japan', dialCode: '81', flag: '🇯🇵' },
  { isoCode: 'JE', name: 'Jersey', dialCode: '44-1534', flag: '🇯🇪' },
  { isoCode: 'JO', name: 'Jordan', dialCode: '962', flag: '🇯🇴' },
  { isoCode: 'KZ', name: 'Kazakhstan', dialCode: '7', flag: '🇰🇿' },
  { isoCode: 'KE', name: 'Kenya', dialCode: '254', flag: '🇰🇪' },
  { isoCode: 'KI', name: 'Kiribati', dialCode: '686', flag: '🇰🇮' },
  { isoCode: 'XK', name: 'Kosovo', dialCode: '383', flag: '🇽🇰' },
  { isoCode: 'KW', name: 'Kuwait', dialCode: '965', flag: '🇰🇼' },
  { isoCode: 'KG', name: 'Kyrgyzstan', dialCode: '996', flag: '🇰🇬' },
  { isoCode: 'LA', name: 'Laos', dialCode: '856', flag: '🇱🇦' },
  { isoCode: 'LV', name: 'Latvia', dialCode: '371', flag: '🇱🇻' },
  { isoCode: 'LB', name: 'Lebanon', dialCode: '961', flag: '🇱🇧' },
  { isoCode: 'LS', name: 'Lesotho', dialCode: '266', flag: '🇱🇸' },
  { isoCode: 'LR', name: 'Liberia', dialCode: '231', flag: '🇱🇷' },
  { isoCode: 'LY', name: 'Libya', dialCode: '218', flag: '🇱🇾' },
  { isoCode: 'LI', name: 'Liechtenstein', dialCode: '423', flag: '🇱🇮' },
  { isoCode: 'LT', name: 'Lithuania', dialCode: '370', flag: '🇱🇹' },
  { isoCode: 'LU', name: 'Luxembourg', dialCode: '352', flag: '🇱🇺' },
  { isoCode: 'MO', name: 'Macau S.A.R.', dialCode: '853', flag: '🇲🇴' },
  { isoCode: 'MK', name: 'Macedonia', dialCode: '389', flag: '🇲🇰' },
  { isoCode: 'MG', name: 'Madagascar', dialCode: '261', flag: '🇲🇬' },
  { isoCode: 'MW', name: 'Malawi', dialCode: '265', flag: '🇲🇼' },
  { isoCode: 'MY', name: 'Malaysia', dialCode: '60', flag: '🇲🇾' },
  { isoCode: 'MV', name: 'Maldives', dialCode: '960', flag: '🇲🇻' },
  { isoCode: 'ML', name: 'Mali', dialCode: '223', flag: '🇲🇱' },
  { isoCode: 'MT', name: 'Malta', dialCode: '356', flag: '🇲🇹' },
  { isoCode: 'IM', name: 'Man (Isle of)', dialCode: '44-1624', flag: '🇮🇲' },
  { isoCode: 'MH', name: 'Marshall Islands', dialCode: '692', flag: '🇲🇭' },
  { isoCode: 'MQ', name: 'Martinique', dialCode: '596', flag: '🇲🇶' },
  { isoCode: 'MR', name: 'Mauritania', dialCode: '222', flag: '🇲🇷' },
  { isoCode: 'MU', name: 'Mauritius', dialCode: '230', flag: '🇲🇺' },
  { isoCode: 'YT', name: 'Mayotte', dialCode: '262', flag: '🇾🇹' },
  { isoCode: 'MX', name: 'Mexico', dialCode: '52', flag: '🇲🇽' },
  { isoCode: 'FM', name: 'Micronesia', dialCode: '691', flag: '🇫🇲' },
  { isoCode: 'MD', name: 'Moldova', dialCode: '373', flag: '🇲🇩' },
  { isoCode: 'MC', name: 'Monaco', dialCode: '377', flag: '🇲🇨' },
  { isoCode: 'MN', name: 'Mongolia', dialCode: '976', flag: '🇲🇳' },
  { isoCode: 'ME', name: 'Montenegro', dialCode: '382', flag: '🇲🇪' },
  { isoCode: 'MS', name: 'Montserrat', dialCode: '1-664', flag: '🇲🇸' },
  { isoCode: 'MA', name: 'Morocco', dialCode: '212', flag: '🇲🇦' },
  { isoCode: 'MZ', name: 'Mozambique', dialCode: '258', flag: '🇲🇿' },
  { isoCode: 'MM', name: 'Myanmar', dialCode: '95', flag: '🇲🇲' },
  { isoCode: 'NA', name: 'Namibia', dialCode: '264', flag: '🇳🇦' },
  { isoCode: 'NR', name: 'Nauru', dialCode: '674', flag: '🇳🇷' },
  { isoCode: 'NP', name: 'Nepal', dialCode: '977', flag: '🇳🇵' },
  { isoCode: 'NL', name: 'Netherlands', dialCode: '31', flag: '🇳🇱' },
  { isoCode: 'NC', name: 'New Caledonia', dialCode: '687', flag: '🇳🇨' },
  { isoCode: 'NZ', name: 'New Zealand', dialCode: '64', flag: '🇳🇿' },
  { isoCode: 'NI', name: 'Nicaragua', dialCode: '505', flag: '🇳🇮' },
  { isoCode: 'NE', name: 'Niger', dialCode: '227', flag: '🇳🇪' },
  { isoCode: 'NG', name: 'Nigeria', dialCode: '234', flag: '🇳🇬' },
  { isoCode: 'NU', name: 'Niue', dialCode: '683', flag: '🇳🇺' },
  { isoCode: 'NF', name: 'Norfolk Island', dialCode: '672', flag: '🇳🇫' },
  { isoCode: 'KP', name: 'North Korea', dialCode: '850', flag: '🇰🇵' },
  { isoCode: 'MP', name: 'Northern Mariana Islands', dialCode: '1-670', flag: '🇲🇵' },
  { isoCode: 'NO', name: 'Norway', dialCode: '47', flag: '🇳🇴' },
  { isoCode: 'OM', name: 'Oman', dialCode: '968', flag: '🇴🇲' },
  { isoCode: 'PK', name: 'Pakistan', dialCode: '92', flag: '🇵🇰' },
  { isoCode: 'PW', name: 'Palau', dialCode: '680', flag: '🇵🇼' },
  { isoCode: 'PS', name: 'Palestinian Territory Occupied', dialCode: '970', flag: '🇵🇸' },
  { isoCode: 'PA', name: 'Panama', dialCode: '507', flag: '🇵🇦' },
  { isoCode: 'PG', name: 'Papua new Guinea', dialCode: '675', flag: '🇵🇬' },
  { isoCode: 'PY', name: 'Paraguay', dialCode: '595', flag: '🇵🇾' },
  { isoCode: 'PE', name: 'Peru', dialCode: '51', flag: '🇵🇪' },
  { isoCode: 'PH', name: 'Philippines', dialCode: '63', flag: '🇵🇭' },
  { isoCode: 'PN', name: 'Pitcairn Island', dialCode: '870', flag: '🇵🇳' },
  { isoCode: 'PL', name: 'Poland', dialCode: '48', flag: '🇵🇱' },
  { isoCode: 'PT', name: 'Portugal', dialCode: '351', flag: '🇵🇹' },
  { isoCode: 'PR', name: 'Puerto Rico', dialCode: '1-787 and 1-939', flag: '🇵🇷' },
  { isoCode: 'QA', name: 'Qatar', dialCode: '974', flag: '🇶🇦' },
  { isoCode: 'RE', name: 'Reunion', dialCode: '262', flag: '🇷🇪' },
  { isoCode: 'RO', name: 'Romania', dialCode: '40', flag: '🇷🇴' },
  { isoCode: 'RU', name: 'Russia', dialCode: '7', flag: '🇷🇺' },
  { isoCode: 'RW', name: 'Rwanda', dialCode: '250', flag: '🇷🇼' },
  { isoCode: 'SH', name: 'Saint Helena', dialCode: '290', flag: '🇸🇭' },
  { isoCode: 'KN', name: 'Saint Kitts And Nevis', dialCode: '1-869', flag: '🇰🇳' },
  { isoCode: 'LC', name: 'Saint Lucia', dialCode: '1-758', flag: '🇱🇨' },
  { isoCode: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '508', flag: '🇵🇲' },
  { isoCode: 'VC', name: 'Saint Vincent And The Grenadines', dialCode: '1-784', flag: '🇻🇨' },
  { isoCode: 'BL', name: 'Saint-Barthelemy', dialCode: '590', flag: '🇧🇱' },
  { isoCode: 'MF', name: 'Saint-Martin (French part)', dialCode: '590', flag: '🇲🇫' },
  { isoCode: 'WS', name: 'Samoa', dialCode: '685', flag: '🇼🇸' },
  { isoCode: 'SM', name: 'San Marino', dialCode: '378', flag: '🇸🇲' },
  { isoCode: 'ST', name: 'Sao Tome and Principe', dialCode: '239', flag: '🇸🇹' },
  { isoCode: 'SA', name: 'Saudi Arabia', dialCode: '966', flag: '🇸🇦' },
  { isoCode: 'SN', name: 'Senegal', dialCode: '221', flag: '🇸🇳' },
  { isoCode: 'RS', name: 'Serbia', dialCode: '381', flag: '🇷🇸' },
  { isoCode: 'SC', name: 'Seychelles', dialCode: '248', flag: '🇸🇨' },
  { isoCode: 'SL', name: 'Sierra Leone', dialCode: '232', flag: '🇸🇱' },
  { isoCode: 'SG', name: 'Singapore', dialCode: '65', flag: '🇸🇬' },
  { isoCode: 'SX', name: 'Sint Maarten (Dutch part)', dialCode: '1721', flag: '🇸🇽' },
  { isoCode: 'SK', name: 'Slovakia', dialCode: '421', flag: '🇸🇰' },
  { isoCode: 'SI', name: 'Slovenia', dialCode: '386', flag: '🇸🇮' },
  { isoCode: 'SB', name: 'Solomon Islands', dialCode: '677', flag: '🇸🇧' },
  { isoCode: 'SO', name: 'Somalia', dialCode: '252', flag: '🇸🇴' },
  { isoCode: 'ZA', name: 'South Africa', dialCode: '27', flag: '🇿🇦' },
  { isoCode: 'GS', name: 'South Georgia', dialCode: '500', flag: '🇬🇸' },
  { isoCode: 'KR', name: 'South Korea', dialCode: '82', flag: '🇰🇷' },
  { isoCode: 'SS', name: 'South Sudan', dialCode: '211', flag: '🇸🇸' },
  { isoCode: 'ES', name: 'Spain', dialCode: '34', flag: '🇪🇸' },
  { isoCode: 'LK', name: 'Sri Lanka', dialCode: '94', flag: '🇱🇰' },
  { isoCode: 'SD', name: 'Sudan', dialCode: '249', flag: '🇸🇩' },
  { isoCode: 'SR', name: 'Suriname', dialCode: '597', flag: '🇸🇷' },
  { isoCode: 'SJ', name: 'Svalbard And Jan Mayen Islands', dialCode: '47', flag: '🇸🇯' },
  { isoCode: 'SZ', name: 'Swaziland', dialCode: '268', flag: '🇸🇿' },
  { isoCode: 'SE', name: 'Sweden', dialCode: '46', flag: '🇸🇪' },
  { isoCode: 'CH', name: 'Switzerland', dialCode: '41', flag: '🇨🇭' },
  { isoCode: 'SY', name: 'Syria', dialCode: '963', flag: '🇸🇾' },
  { isoCode: 'TW', name: 'Taiwan', dialCode: '886', flag: '🇹🇼' },
  { isoCode: 'TJ', name: 'Tajikistan', dialCode: '992', flag: '🇹🇯' },
  { isoCode: 'TZ', name: 'Tanzania', dialCode: '255', flag: '🇹🇿' },
  { isoCode: 'TH', name: 'Thailand', dialCode: '66', flag: '🇹🇭' },
  { isoCode: 'BS', name: 'The Bahamas', dialCode: '1-242', flag: '🇧🇸' },
  { isoCode: 'GM', name: 'The Gambia', dialCode: '220', flag: '🇬🇲' },
  { isoCode: 'TG', name: 'Togo', dialCode: '228', flag: '🇹🇬' },
  { isoCode: 'TK', name: 'Tokelau', dialCode: '690', flag: '🇹🇰' },
  { isoCode: 'TO', name: 'Tonga', dialCode: '676', flag: '🇹🇴' },
  { isoCode: 'TT', name: 'Trinidad And Tobago', dialCode: '1-868', flag: '🇹🇹' },
  { isoCode: 'TN', name: 'Tunisia', dialCode: '216', flag: '🇹🇳' },
  { isoCode: 'TR', name: 'Turkey', dialCode: '90', flag: '🇹🇷' },
  { isoCode: 'TM', name: 'Turkmenistan', dialCode: '993', flag: '🇹🇲' },
  { isoCode: 'TC', name: 'Turks And Caicos Islands', dialCode: '1-649', flag: '🇹🇨' },
  { isoCode: 'TV', name: 'Tuvalu', dialCode: '688', flag: '🇹🇻' },
  { isoCode: 'UG', name: 'Uganda', dialCode: '256', flag: '🇺🇬' },
  { isoCode: 'UA', name: 'Ukraine', dialCode: '380', flag: '🇺🇦' },
  { isoCode: 'AE', name: 'United Arab Emirates', dialCode: '971', flag: '🇦🇪' },
  { isoCode: 'GB', name: 'United Kingdom', dialCode: '44', flag: '🇬🇧' },
  { isoCode: 'US', name: 'United States', dialCode: '1', flag: '🇺🇸' },
  { isoCode: 'UM', name: 'United States Minor Outlying Islands', dialCode: '1', flag: '🇺🇲' },
  { isoCode: 'UY', name: 'Uruguay', dialCode: '598', flag: '🇺🇾' },
  { isoCode: 'UZ', name: 'Uzbekistan', dialCode: '998', flag: '🇺🇿' },
  { isoCode: 'VU', name: 'Vanuatu', dialCode: '678', flag: '🇻🇺' },
  { isoCode: 'VA', name: 'Vatican City State (Holy See)', dialCode: '379', flag: '🇻🇦' },
  { isoCode: 'VE', name: 'Venezuela', dialCode: '58', flag: '🇻🇪' },
  { isoCode: 'VN', name: 'Vietnam', dialCode: '84', flag: '🇻🇳' },
  { isoCode: 'VG', name: 'Virgin Islands (British)', dialCode: '1-284', flag: '🇻🇬' },
  { isoCode: 'VI', name: 'Virgin Islands (US)', dialCode: '1-340', flag: '🇻🇮' },
  { isoCode: 'WF', name: 'Wallis And Futuna Islands', dialCode: '681', flag: '🇼🇫' },
  { isoCode: 'EH', name: 'Western Sahara', dialCode: '212', flag: '🇪🇭' },
  { isoCode: 'YE', name: 'Yemen', dialCode: '967', flag: '🇾🇪' },
  { isoCode: 'ZM', name: 'Zambia', dialCode: '260', flag: '🇿🇲' },
  { isoCode: 'ZW', name: 'Zimbabwe', dialCode: '263', flag: '🇿🇼' },
]
