'use client'

export {
  Check as CheckIcon,
  CheckCircle as CheckCircleIcon,
  Info as InfoIcon,
  TriangleAlert as WarningIcon,
  X as XIcon,
  XCircle as XCircleIcon,
  Loader2 as SpinnerIcon,
  ChevronRight as CaretRightIcon,
  House as HouseIcon,
  BookOpen as BookOpenIcon,
  Users as UsersIcon,
  Calendar as CalendarBlankIcon,
  User as UserIcon,
  TrendingUp as TrendUpIcon,
  Bookmark as BookmarkSimpleIcon,
  Video as VideoCameraIcon,
  ExternalLink as ArrowSquareOutIcon,
  Clock as ClockIcon,
  ClipboardList as ExamIcon,
  ChevronDown as CaretDownIcon,
  Settings as SettingsIcon,
  LogOutIcon as LeaveIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Menu as HamburgerIcon,
} from 'lucide-react'
