export * from './auth'
export * from './school'
export * from './relations'

import { user, session, account, verification, organization, member, invitation } from './auth'
import {
  profile,
  track,
  chapter,
  chapterScript,
  segment,
  chapterScriptSegment,
  audioAsset,
  audioMapping,
  stagedUpload,
  batch,
  batchClassSlot,
  enrollment,
  evaluation,
  exam,
  trackCertification,
} from './school'
import {
  userRelations,
  sessionRelations,
  accountRelations,
  organizationRelations,
  memberRelations,
  invitationRelations,
  profileRelations,
  trackRelations,
  chapterRelations,
  chapterScriptRelations,
  segmentRelations,
  chapterScriptSegmentRelations,
  audioAssetRelations,
  audioMappingRelations,
  batchRelations,
  batchClassSlotRelations,
  enrollmentRelations,
  evaluationRelations,
  examRelations,
  trackCertificationRelations,
} from './relations'

/** BetterAuth + organization tables and their relations. Backs PublicDbClient's `.query` surface. */
export const publicSchema = {
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation,
  userRelations,
  sessionRelations,
  accountRelations,
  organizationRelations,
  memberRelations,
  invitationRelations,
}

/** Profile/content/batch/enrollment/exam/evaluation tables and their relations. Backs SchoolDbClient's `.query` surface. */
export const schoolSchema = {
  profile,
  track,
  chapter,
  chapterScript,
  segment,
  chapterScriptSegment,
  audioAsset,
  audioMapping,
  stagedUpload,
  batch,
  batchClassSlot,
  enrollment,
  evaluation,
  exam,
  trackCertification,
  profileRelations,
  trackRelations,
  chapterRelations,
  chapterScriptRelations,
  segmentRelations,
  chapterScriptSegmentRelations,
  audioAssetRelations,
  audioMappingRelations,
  batchRelations,
  batchClassSlotRelations,
  enrollmentRelations,
  evaluationRelations,
  examRelations,
  trackCertificationRelations,
}
